# Generated by Django 3.1.4 on 2020-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_choice_1', models.CharField(max_length=50)),
                ('question_choice_2', models.CharField(max_length=50)),
                ('question_choice_3', models.CharField(max_length=50)),
                ('question_choice_4', models.CharField(max_length=50)),
                ('question_source', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
