# Generated by Django 3.1.4 on 2020-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0003_question_question_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_subject',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_source',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
